title: Shannon # your name (or website title) here
logo: "/images/Shannon-prof-profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  I am a web developer and designer with a passion for transforming peopleâ€™s raw ideas into beautiful responsive websites that tell their stories and depict their vision.
  <br><br>

  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here




 
